(function(){
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const modes=[
    {name:'Voice Mode',tag:'VOICE-FIRST',title:'Speak the goal. Keep the thread.',desc:'A low-friction voice surface for continuing work, asking for status and routing commands without losing the active project context.'},
    {name:'File Intelligence',tag:'RETRIEVAL',title:'Files ranked by meaning, not folders.',desc:'A project-aware view that surfaces the files most relevant to the current objective and explains why each one matters.'},
    {name:'Memory Manager',tag:'CONTINUITY',title:'See what the system remembers.',desc:'Inspectable project memory with decisions, resume points and evidence — designed to make persistence understandable and controllable.'},
    {name:'Agent Control',tag:'ORCHESTRATION',title:'One objective. Multiple specialists.',desc:'A control room for seeing which specialist is active, what it is doing, which tools it can access and how outputs reconnect.'},
    {name:'Projects',tag:'WORKSPACE',title:'Your work organized around goals.',desc:'Projects become living threads with active context, recent changes, next actions and connected resources instead of static folders.'},
    {name:'Privacy / Local',tag:'CONTROL',title:'Know where intelligence is running.',desc:'A settings surface for local-vs-cloud routing, permissions, data boundaries and tool access so capability stays visible and intentional.'}
  ];
  function panelMarkup(i){
    if(i===0)return `<div class="suite-voice"><div class="voice-radar"><i></i><i></i><i></i><b></b></div><div class="voice-transcript"><small>LIVE INTENT</small><h4>“Continue the website and show me what changed.”</h4><div class="voice-bars">${Array.from({length:22},(_,n)=>`<i style="--h:${20+(n*17)%70}%"></i>`).join('')}</div><span>THREAD / JARVIS OS WEBSITE</span></div><aside><small>ROUTE</small><strong>Designer → Builder</strong><p>Context restored before execution.</p></aside></div>`;
    if(i===1)return `<div class="suite-files"><aside>${['styles.css','inside-jarvis.js','intro-core.js','README.md','invoice.pdf'].map((x,n)=>`<button class="${n===0?'active':''}"><span>${String(n+1).padStart(2,'0')}</span><b>${x}</b><em>${[.96,.91,.87,.64,.12][n]}</em></button>`).join('')}</aside><main><small>MOST RELEVANT / 0.96</small><h4>styles.css</h4><p>Controls the visual system that defines hero scale, section choreography, responsive behavior and product identity.</p><div class="file-reasons"><span>visual system</span><span>hero core</span><span>motion</span><span>responsive</span></div><div class="file-code">${Array.from({length:10},(_,n)=>`<i style="width:${45+(n*13)%50}%"></i>`).join('')}</div></main></div>`;
    if(i===2)return `<div class="suite-memory"><div class="memory-column"><article><small>DECISION / 01</small><strong>Keep desktop shell separate from agent runtime.</strong><span>Evidence: architecture notes</span></article><article class="current"><small>RESUME POINT</small><strong>Finish cinematic system journey.</strong><span>Active now</span></article><article><small>NEXT / 03</small><strong>Connect real product states when runtime matures.</strong><span>Planned</span></article></div><aside><small>MEMORY HEALTH</small><div><span>Traceable</span><b>92%</b></div><div><span>Recent</span><b>88%</b></div><div><span>Relevant</span><b>95%</b></div><p>Concept UI: memory should be inspectable, not mysterious.</p></aside></div>`;
    if(i===3)return `<div class="suite-agents"><div class="agent-map"><div class="suite-agent-core">OBJECTIVE<small>Ship website V5</small></div>${['Builder','Researcher','Designer','Archivist'].map((x,n)=>`<div class="suite-agent a${n}"><span>${x}</span><small>${['CODE + VERIFY','SEARCH + CITE','UI + MOTION','FILES + MEMORY'][n]}</small></div>`).join('')}<svg viewBox="0 0 100 100" preserveAspectRatio="none"><path d="M50 50 L18 18M50 50 L82 18M50 50 L18 82M50 50 L82 82"/></svg></div><aside><small>ACTIVE SPECIALIST</small><strong>DESIGNER</strong><p>Interface direction · motion language · visual QA</p><div><span>TOOLS</span><b>Workspace / GitHub</b></div><div><span>STATUS</span><b>Executing</b></div></aside></div>`;
    if(i===4)return `<div class="suite-projects"><aside><span class="active">Jarvis OS</span><span>Weed Robot</span><span>FreshFusion</span><span>SIH Research</span></aside><main><div class="project-head"><div><small>ACTIVE PROJECT</small><h4>Jarvis OS</h4></div><b>68% / VISION BUILD</b></div><div class="project-cards"><article><small>RECENT</small><strong>Interactive website architecture expanded</strong><span>12 files changed</span></article><article><small>NEXT</small><strong>Inside Jarvis cinematic journey</strong><span>priority / P0</span></article><article><small>BLOCKED</small><strong>Real runtime state integration</strong><span>depends on product backend</span></article></div><div class="project-thread"><span>THREAD</span><p>“Continue from where we stopped.”</p><button>RESUME ↗</button></div></main></div>`;
    return `<div class="suite-privacy"><div class="privacy-core"><span>ROUTING POLICY</span><strong>LOCAL-FIRST</strong><div class="privacy-ring"><i></i><i></i><i></i></div></div><div class="privacy-grid"><article><small>FILES</small><strong>LOCAL</strong><p>Keep project file indexing on device.</p></article><article><small>VOICE</small><strong>HYBRID</strong><p>Prefer local capture, route only when needed.</p></article><article><small>WEB RESEARCH</small><strong>CLOUD</strong><p>External access required for current sources.</p></article><article><small>TOOL ACTIONS</small><strong>CONFIRM</strong><p>Explicit boundary for sensitive operations.</p></article></div></div>`;
  }
  function inject(){
    const anchor=$('.roadmap');if(!anchor||$('#product-suite'))return;
    const section=document.createElement('section');section.id='product-suite';section.className='product-suite section-pad';
    section.innerHTML=`<div class="section-head"><span>06.9 / PRODUCT SYSTEM</span><span>MAKE THE FUTURE FEEL OPERABLE.</span></div><div class="suite-intro"><div><p class="micro-label">CONCEPT INTERFACES</p><h2>SIX VIEWS.<br><span>ONE</span><br><em>SYSTEM.</em></h2></div><p>These screens are interface direction for Jarvis OS — not claims that the complete desktop runtime exists today. The goal is to make the product vision concrete enough to critique and build.</p></div><div class="suite-shell" data-suite-shell><aside class="suite-tabs">${modes.map((m,i)=>`<button type="button" data-suite-tab="${i}" class="${i===0?'active':''}"><small>0${i+1}</small><span>${m.name}</span><em>${m.tag}</em></button>`).join('')}</aside><main class="suite-screen"><div class="suite-bar"><span>JARVIS / PRODUCT DECK</span><div><small>CONCEPT UI</small><button type="button" data-suite-fullscreen>EXPAND ↗</button></div></div><div class="suite-screen-head"><div><small data-suite-tag>${modes[0].tag}</small><h3 data-suite-title>${modes[0].title}</h3></div><p data-suite-desc>${modes[0].desc}</p></div><div class="suite-visual" data-suite-visual>${panelMarkup(0)}</div><div class="suite-footer"><span>INTERFACE DIRECTION / NOT FINISHED RUNTIME</span><span data-suite-index>01 / 06</span></div></main></div>`;
    anchor.insertAdjacentElement('beforebegin',section);
  }
  function interact(){const root=$('#product-suite');if(!root)return;const tabs=$$('[data-suite-tab]',root),visual=$('[data-suite-visual]',root),title=$('[data-suite-title]',root),tag=$('[data-suite-tag]',root),desc=$('[data-suite-desc]',root),index=$('[data-suite-index]',root),shell=$('[data-suite-shell]',root);function activate(i){tabs.forEach((x,n)=>x.classList.toggle('active',n===i));visual.classList.add('switching');setTimeout(()=>{visual.innerHTML=panelMarkup(i);title.textContent=modes[i].title;tag.textContent=modes[i].tag;desc.textContent=modes[i].desc;index.textContent=`0${i+1} / 06`;visual.classList.remove('switching');},160);window.dispatchEvent(new CustomEvent('jarvis:state',{detail:{state:i===0?'listening':i===3?'routing':i===5?'verified':'thinking',source:'product-suite',hold:1200}}));}tabs.forEach((b,i)=>b.addEventListener('click',()=>activate(i)));$('[data-suite-fullscreen]',root)?.addEventListener('click',()=>{shell.classList.toggle('expanded');document.body.classList.toggle('is-locked',shell.classList.contains('expanded'));});addEventListener('keydown',e=>{if(e.key==='Escape'&&shell.classList.contains('expanded')){shell.classList.remove('expanded');document.body.classList.remove('is-locked');}})}
  function init(){inject();interact()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();